### ISSUE TITLE
Unittest general setup discussion (request for comments)

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/multilingual-press#101]
In order to implement automated tests we should determine how to organize these tests on a code base.

As PHPUnit is the most common testing framework I think we should build up on this one and set it as a basic requirement for using/developing the tests. For more dependencies (e.g. Mockery) we could use composer on a dev-dependency level. 

For performance and flexibility reasons we should split plain unit tests (only testing the MLP code itself) and integration tests with WordPress using the WordPress test framework into two separate procedures with two PHPUnit configuration files and two separate bootstrap processes. 

Here's a suggestion of the directory structure based on my thoughts above:
```
 multilingual-press/
    ├ inc/
    ├ …/
    └ test/
        ├ inc/
        │   ├  autoload.php
        │   └  …
        ├ Unit
        │   ├ phpunit.xml.dist
        │   ├ bootstrap.php
        │   └ Common/
        │         ├   Mlp_Admin_Notice_Test.php
        │         └   …
        └ WPIntegration
             ├ phpunit.xml.dist
             ├ bootstrap.php
             └ Common/
                   ├ Mlp_Admin_Notice_Test.php
                   └   …
```

I'm interested in everybody's opinion but specially from @tfrommen and @toscho

**Comment by tfrommen** [comment]
Firstly, I absolutely agree that different types of tests should be separated from each other.
Secondly, we definitely want unit tests (which in our case are basically function-specific tests).

What I don't like that much is the separation into _Unit_ and _WordPress-Integration_ tests. Why is that? Because there is something in between. Integration tests are about testing _packages_ and their _interfaces_. So what I want to say is, we should also test certain _parts_ of MLP, and just MLP. The next step would then be to test MLP (or parts of the plugin) and its interfaces with WordPress. When seeing MLP as central point, this would, in fact, be something between integration and system tests.

Also, MLP is more than just PHP. We should also consider using QUnit or something similar to test MLP's JavaScript part.

**Comment by dnaber-de** [comment]
>  Why is that? 

Because the WP test core initialization is _really_ slow. That makes it nearly impossible to use tests during the development. Believe me, you don't want to run the tests frequently when every run takes 2 seconds or more.

One important point I missed out is that in this case every dependency has to be decelerated somewhere else because WordPress does not allow to just load the core files without starting to execute code. Thats the opposite of this approach. 

> Integration tests are about testing packages and their interfaces.

What does that mean for MLP and WordPress. Or in other words: how would name tests which test the interaction of the WordPress core code with the MLP code?

**Comment by tfrommen** [comment]
Well, it seems you misunderstood me, a little. With _Why is that?_ I didn't want to question your approach. I wanted to question (and then clarify) my dislike of separation into (only) _Unit_ and _WordPress-Integration_. Just because there is also _Integration_ without WordPress being involved. :)

If we name the tests where WordPress is involved _WordPress Integration_ tests or _System_ tests&mdash;I'm fine with either. My comment wasn't aiming for the name per se, but for the lack of _MLP Integration_ tests.

**Comment by kraftner** [comment]
I wonder if there even really is the option to leave WP out of the equation. There are WP hooks all over the place, I wonder how much you can really test without running the code together with WP.

**Comment by tfrommen** [comment]
Unit-testing a plugin is *all about* testing it *without* WordPress. That's what mocks/stubs/phrophets and all such things are there for.

But of course we would have (and want) to do integration tests, too.

**Comment by kraftner** [comment]
I just imagine this being difficult. But I don't really have enough experience with unit tests to bring any value to this discussion. I'll just retreat to other issues and watch in awe as it unfolds. :wink:

**Comment by tfrommen** [comment]
As discussed in our internal developer meetings, we will (soon) manage our tests in the following directory structure:

```
multilingualpress/
|-- ...
|-- tests/
|   |-- phpunit/
|   |   |-- integration/
|   |   |   |-- SomeTest.php
|   |   |   `-- ...
|   |   |-- system/
|   |   |   |-- SomeTest.php
|   |   |   `-- ...
|   |   |-- unit/
|   |   |   |-- SomeTest.php
|   |   |   `-- ...
|   |   |-- bootstrap.php
|   |   `-- ...
|   |-- qunit/
|   |   |-- unit/
|   |   |   |-- some-test.js
|   |   |   `-- ...
|   |   `-- ...
|   `-- ...
|-- ...
|-- phpunit.xml.dist
`-- ...
```

with `phpunit.xml.dist` being this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    bootstrap="tests/phpunit/bootstrap.php"
    backupGlobals="false"
    colors="true"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    >
    <testsuites>
        <testsuite name="unit">
            <directory suffix="Test.php">tests/phpunit/unit</directory>
        </testsuite>
        <testsuite name="integration">
            <directory suffix="Test.php">tests/phpunit/integration</directory>
        </testsuite>
        <testsuite name="system">
            <directory suffix="Test.php">tests/phpunit/system</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

**Comment by tfrommen** [comment]
Closed with https://github.com/inpsyde/multilingual-press/commit/286775c5cd9f7995552f525db29e942c8f606adb.
