### ISSUE TITLE
Term translations are broken

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#135]
## ALL Testing and Development happens in that branch. Do NOT work on it while still being on 'master'

There is an issue with assigning/editing/removing term translations. 

### How to test:

 * **Make sure** you are on the ['bug/term_translation'-branch](https://github.com/inpsyde/multilingual-press/tree/bug/term_translation) as mentioned at the beginning of this Issue
 * Truncate *_mlp_linked table so that you're working with a clean slate
 * Setup an MLP/MS installation with at least 2 sites (better create 3)
 * Create a new term on site A
 * Change to site B
 * Create a new term on site B and link it to the term you created on site A
 * For bonus points, do the same with site C

### Expected results:
 - All terms should show up as connected to their respective translations
 - They should be linked in the language switcher widget

While we're getting mixed feedback on this, it seems to indicate that this feature is broken for many users.
Test results range from **working** to **almost entirely broken**

[Here is a Screencast demonstrating the problem](https://biont.ursa.uberspace.de/sharex/bilder/2015-07-23_15-56-02.mp4)

We would appreciate any additional feedback about this problem

**Comment by deantomasevic** [comment]
**Testcase:**

* Truncate *_mlp_linked table so that you're working with a clean slate
* Setup an MLP/MS installation with at least 4 sites (en, fr, es, no)
* Create a new term on site 'no' & set the "german translation to "melonen" (right area in screenshot)
* Change to next site & create a new term (do it for all language sites)
* Go back to MPL installation (multisite page) and go to terms menue
* Go to term "melonen" and set all translations (left area in screenshot)
* Save term
* Reload page - everything is fine and all term translations for term "melonen" are loaded

![Demo](https://picload.org/image/ipgwwpo/screenshot2015-07-2711.16.03.png)

**Comment by deantomasevic** [comment]
Add a small fix:

Commit: 7a4530a609f5b979624fdf60903e11ef7cbd88fd

![Demo](http://s21.postimg.org/et2tw76x3/Screenshot_2015_07_27_12_37_46.png)

**Comment by Giede** [comment]
@tfrommen I tested your fix and it works fine, thanks.
