### ISSUE TITLE
MLP 2.4.0: Fatal error (only backend) after update

### ISSUE THREAD

**Issue by tyrann0us** [inpsyde/multilingual-press#204]
#### Version information
* WordPress: 4.5.2
* MultilingualPress: 2.4.0
* PHP: 5.3.10 (FastCGI)

#### Steps to reproduce
1. Update to latest MLP
2. Try to access backend (wp-admin/)

#### What I expected
Fully functional backend

#### What happened instead
Error 500 with following error message:
```Catchable fatal error: Argument 1 passed to Mlp_Self_Check::remove_mlp_from_update_plugins_transient() must be an instance of stdClass, boolean given in /var/www/vhosts/example.com/httpdocs/wp-content/plugins/multilingual-press/inc/installation/Mlp_Self_Check.php on line 146```

What other information/logs to you need?

**Comment by tfrommen** [comment]
@tyrann0us thanks, the information was (good) enough.

I already fixed this in the 2.4 branch. You can expect a patch release soon.

**For now** you could just remove `stdClass` in the line mentioned in your error message, **or** temporarily rename the `multilingual-press` folder (and thus deactivate the plugin), visit the Plugins page in your main site's WordPress Admin, and then undo the renaming, and reactivate MultilingualPress. The reason for the error message is that you don't seem to have ever checked for plugin updates...?

BTW, in order to continue with MultilingualPress, you will have to update PHP to version 5.4+ for the **next major release**.
