### ISSUE TITLE
Error with title and meta descriptions

### ISSUE THREAD

**Issue by hcortesb** [inpsyde/multilingual-press#210]
#### Version Information
* WordPress: 4.5.2
* MultilingualPress: 2.4.1
* Genesis Theme: 2.2.7

I have several languages configured (en,es,fr,it,de) and when I set the meta description and the title in one language at the Theme SEO Settings, it overwrites the meta description and the title in all the other languages.

**Comment by tfrommen** [comment]
This is (most likely) a problem with your theme as MultilingualPress does not manipulate (even unknown, third-party) metadata.
Please contact the folks responsible for the Genesis theme.

The fix is most likely something simple like this:

```php
if ( is_multisite() && ms_is_switched() ) {
    return (false|null|whatever);
}
```

I just solved the exact same thing for the [Yoast SEO](https://github.com/Yoast/wordpress-seo/pull/4557) plugin.

I'll close this for now.
