### ISSUE TITLE
4.6 Deprecated wp_get_sites

### ISSUE THREAD

**Issue by sfisherGizmo** [inpsyde/multilingual-press#229]
#### Version Information
* WordPress: 4.6
* MultilingualPress: 2.4.7

PHP Notice is given due to deprecation of `wp_get_sites()` in Wordpress 4.6. Should now use`get_sites()`. Please see ticket here, https://core.trac.wordpress.org/ticket/36994

**Comment by bueltge** [comment]
Is implemented in the source - https://github.com/inpsyde/multilingual-press/commit/1856b7ecd958c703720a8d4def767c4ab9c7f8b2

**Comment by tfrommen** [comment]
As @bueltge already pointed out, this is already [included in the `master`](https://github.com/inpsyde/multilingual-press/commit/1856b7ecd958c703720a8d4def767c4ab9c7f8b2), but **not** shipped in the latest patch update (i.e., MultilingualPress 2.4.7). `wp_get_sites()` does still work, and due to our policy of staying backcompat with two major versions back, the change is (in my opinion) too much for a **patch** release. The function didn't just get renamed, it also returns completely different things now.
