### ISSUE TITLE
Custom Field values are synced across different language sites

### ISSUE THREAD

**Issue by defries** [inpsyde/multilingual-press#235]
#### Version Information
- WordPress: 4.6.1
- MultilingualPress: 2.4.7
#### Steps to Reproduce
1. Create custom meta boxes with CMB2 (for a post, page, page template – doesn't really matter what)
2. Enter values in the CMB2 metaboxes on the English site for example
3. Wanting to enter values in the CMB2 metaboxes settings for the German site for example, but ...
#### What I Expected

I expected the German site to not have the values of the custom fields/metabox entries of the English to be filled in the German site. 
#### What Happened Instead

The values were already filled, but even worse, if I change the values of those metaboxes on the German site, than those are synced back to the English site.

I think I remember @ryanhellyer posting a similar ticket here a few months back, but I couldn't find it.

**Comment by tfrommen** [comment]
Yes, there already is an issue for this, [in the WordPress.org support forums](https://wordpress.org/support/topic/bug-in-lastest-version/). There even is an issue created [on the CMB2 GitHub repo](https://github.com/humanmade/Custom-Meta-Boxes/issues/335) by a colleague of mine.

As far as we see it, CMB2 is lacking a check for the site context.

**Comment by defries** [comment]
You're linking to the Custom MetaBoxes Library from Human Made, but we're using CMB2 Metabox library here. The issue happens with both libraries btw and since older version of MLP were not having this issue, it sounds logical to me that the issue lies within MLP and not the various metabox libraries.

**Comment by defries** [comment]
And for the record, version 2.3.2 doesn't have this issue either.

**Comment by mbootsman** [comment]
I can only emphasize what @defries says. The problem seem to lie in the newer versions of MLP after 2.3.2. What changed that can cause this behaviour?

**Comment by mbootsman** [comment]
My custom metabox code, does not use anything that is stated here: https://developer.wordpress.org/reference/functions/add_meta_box/#comment-1744

It seems that after 2.3.2, MLP has removed code that covers this, and this results in what we are seeing know.

**Comment by defries** [comment]
I would ❤️ it if we could get an answer on this because as it stands, we
have no path forward which means we're stuck in an old version.

**Comment by tfrommen** [comment]
Hi @defries and @mbootsman,

I'm going to leave a short reply here for now, and will respond in more detail hopefully tomorrow.

Sorry for using the _wrong_ meta box lib. You referenced Ryan's issue so I misread it like you had the exact same problem (and not a similar one with another library).

> @defries: ...as it stands, we have no path forward which means we're stuck in an old version.

I'm sorry you see it that way.
We see/assume the problem somewhere else, though. Which does not mean that we won't try to address it. We definitely will.

> @mbootsman: The problem seem to lie in the newer versions of MLP after 2.3.2. What changed that can cause this behaviour?

The [release notes](https://github.com/inpsyde/multilingual-press/releases/tag/v2.4.0) list what changed from 2.3.x to 2.4.0. On the first glimpse, I don't see anything specific that might cause this.

This issue lists MultilingualPress 2.4.7 as buggy, and you both stated 2.3.2 is working just fine.
Does this mean that you have that problem starting with 2.4.0? Or did you just choose the latest 2.3 version for testing?
I'm just asking because [2.4.6 introduced two changes](https://github.com/inpsyde/multilingual-press/releases/tag/v2.4.6) to saving post data that _might_ have to do with this. If 2.4.0 isn't working for you as well, though, then it has to be something else.

**I will have a deeper look into this very soon!**

Thanks,
Thorsten

**Comment by defries** [comment]
Thanks @tfrommen for your reply. We need to do some solid testing from version to version to see where the issue rises, but AFAIK @ryanhellyer had already done this and concluded the 2.3.2 was the last proper working version. But that also might be an incorrect assumption on my part.

Either way, I'll confirm back here once we're done testing.

**Comment by tfrommen** [comment]
I don't know if you already saw this, @defries and @mbootsman, but CMB2 has been updated, and now takes the site context into account (exactly like we suggested): https://de.wordpress.org/plugins/cmb2/changelog/

I guess this solves your issue (and at the same time explains why I didn't have it all the time :) ).

Best regards,
Thorsten

**Comment by defries** [comment]
I hadn't, no, but I was half way done with testing. Will test if CMB2 2.2.3 fixes the bug and report back here.

**Comment by mbootsman** [comment]
Back again.
I have tested this thoroughly and cannot find this bug in version 2.4.8.

Without changing our own code (which registers meta fields and hooks to the `save_post` hook, we cannot reproduce this. Which is good :+1:

**Comment by tfrommen** [comment]
So, can this issue be closed then, @defries? Or is there anything left to do?

Thanks,
Thorsten

**Comment by tfrommen** [comment]
So, can this issue be closed then, @defries? Or is there anything left to do?

Thanks,
Thorsten

**Comment by defries** [comment]
Apologies for the delay, I'll let you know before the end of the week. Verspreche ich.

**Comment by defries** [comment]
Confirming it's no longer an issue for us anymore either 👍
