### ISSUE TITLE
Creating new site - "Based on site" field gets reset on error

### ISSUE THREAD

**Issue by pavel-rybnicek** [inpsyde/multilingual-press#239]
#### Version Information
* WordPress: 4.6.1
* MultilingualPress: 2.4.7

#### Steps to Reproduce
1. Add new site
2. Don't fill the Admin e-mail, submit. You receive the error message.
3. Press the browser Back button. All the input fields keep its values, only the "Based on site" is left empty.

#### What I Expected
I expected this field to keep the value chosen. Didn't notice that, finally have been surprised that the new site is empty.

**Comment by tfrommen** [comment]
Hi,

I'm afraid there isn't much we can do here.

Displaying `<select />` elements differs from browser to browser. And since some of them are _caching_ values even when you do **not** want them to, we added `autocomplete="off"`. What this means for a specific browser also varies, unfortunately.

I understand that this might cause unexpected behavior ins **some** situations. I do hope, though, that in **most** situations you get what you'd expect.

Best regards,
Thorsten
