### ISSUE TITLE
Language menu-item return site_url instead of home_url

### ISSUE THREAD

**Issue by ptrckvzn** [inpsyde/multilingual-press#247]
#### Version Information
* WordPress: 4.7
* MultilingualPress: 2.4.8

#### Steps to Reproduce
1. Create a multisite installation with WordPress in subfolder /wp
2. Define WP_HOME to example.com and WP_SITEURL to example.com/wp in PHP config
3. Add 2 blogs (main + 1) with a menu with a language menu-item pointing to the translation
4. On second blog's front page, check the returned site_url for main blog

#### What I Expected
I am expecting it to return home_url (example.com).

#### What Happened Instead
On main blog, the language menu item return proper front-page site url for other blog translation. But, on second blog, the language menu item returned for front-page of main blog is site_url (example.com/wp).

I was able to fix this by changing get_site_url to get_home_url [here](https://github.com/inpsyde/multilingual-press/blob/7ca5d03c103919e3d7e70eab20de262f6b4738b6/src/inc/language-api/Mlp_Language_Api.php#L312)

Is this the proper behavior? Should the url returned be home_url instead of site_url?

#### Notes
I am using Roots' project structure [Bedrock](https://github.com/roots/bedrock)

**Comment by ptrckvzn** [comment]
Hello, I just noticed that the error reported here happens when main blog is set to a static front-page and the second blog is set to 'latest posts'. After setting both with a static front-page, both front-page returned are OK in the language nav item. So, I don't know if this is worth investigating further as most installation will have the same settings (static vs latest posts) for the front-page. If I can be of further help, I'd be more than happy to report back here.

**Comment by tfrommen** [comment]
Hi there,

I had scheduled this issue for today already. :)

Even if you're right, the current behavior is not 100% correct, still.
For front-end requests/URLs, we should be using `[get_]home_url()` (instead of `[get_]site_url()`). This is not only the case in [the location you linked to](https://github.com/inpsyde/multilingual-press/blob/7ca5d03c103919e3d7e70eab20de262f6b4738b6/src/inc/language-api/Mlp_Language_Api.php#L312), but also in [other](https://github.com/inpsyde/multilingual-press/blob/d3875a7f61ff14d6d6f534a2574aa106d5b3b3fa/src/inc/advanced-translator/Mlp_Cpt_Translator.php#L323) [locations](https://github.com/inpsyde/multilingual-press/blob/d3875a7f61ff14d6d6f534a2574aa106d5b3b3fa/src/inc/nav-menu/Mlp_Nav_Menu_Frontend.php#L129).

I will handle this in a feature branch, so we both can test this before I will merge this.

Thanks,
Thorsten

**Comment by tfrommen** [comment]
Hey @ptrckvzn,

if you have some time, you could try and see if the changes in the [new branch](https://github.com/inpsyde/multilingual-press/tree/issue/247_home_url) are working fine for you as well. :)

Thanks,
Thorsten

**Comment by tfrommen** [comment]
Closed with 0c3de80b9c02a84977c8c89b4368f7364e547b25.
